words_to_remove = {
    "cv",
    "curriculum",
    "currículum",
    "resume",
    "resumé",
    "documento",
    "archivo",
    "file",
    "doc",
    "vitae",
    "version",
    "v.",
    "v1",
    "v2",
    "v3",
    "ok",
    "2023",
    "2024",
    "2025",
    "2026",
    "01",
    "02",
    "03",
    "04",
    "05",
    "06",
    "07",
    "08",
    "09",
    "10",
    "11",
    "12",
    "final",
    "ultima",
    "ultimo",
    "latest",
}


common_skills_keywords = [
    "Python",
    "JavaScript",
    "React",
    "Node.js",
    "SQL",
    "Git",
    "Docker",
    "AWS",
    "Azure",
    "Machine Learning",
    "Data Analysis",
    "Comunicación",
    "Liderazgo",
    "Trabajo en equipo",
    "Resolución de problemas",
    "Excel",
    "Word",
    "PowerPoint",
    "Marketing Digital",
    "Ventas",
    "Atención al cliente",
    "Contabilidad",
    "Finanzas",
    "Java",
    "C++",
    "C#",
    "Scrum",
    "Agile",
    "Linux",
    "Windows Server",
    "Networking",
    "SEO",
    "SEM",
    "UX/UI",
    "Diseño Gráfico",
    "Autocad",
    "SolidWorks",
    "Mantenimiento",
    "Producción",
    "Logística",
    "Inventario",
    "SAP",
    "CRM",
    "Negociación",
    "Project Management",
    "Power BI",
    "Tableau",
    "trabajo en equipo",
    "responsabilidad",
    "puntualidad",
    "comunicación",
    "proactividad",
    "flexibilidad",
    "organización",
    "aprendizaje continuo",
    "adaptabilidad",
    "resolución de problemas",
    "liderazgo",
    "empatía",
    "iniciativa",
    "tolerancia al estrés",
    "resiliencia",
    "autonomía",
    "creatividad",
    "ética laboral",
    "orientación al cliente",
    "disciplina",
    "compromiso",
    "colaboración",
    "capacidad de análisis",
    "honestidad",
    "motivación",
    "PRL",
    "carretillero",
    "elevadora",
    "adaptación",
]


language_levels = [
    "nativo",
    "avanzado",
    "intermedio",
    "básico",
    "fluido",
    "bilingual",
    "conversational",
    "professional",
]

language_names = [
    "español",
    "spanish",
    "inglés",
    "english",
    "francés",
    "french",
    "alemán",
    "german",
    "italiano",
    "italian",
    "portugués",
    "portuguese",
    "chino",
    "chinese",
    "japonés",
    "japanese",
]

summary_section_keywords = [
    "resumen",
    "perfil profesional",
    "acerca de mí",
    "sobre mi",
    "objetivo",
    "perfil",
    "mi perfil",
    "objetivo profesional",
    "summary",
    "profile",
]
