JOB_CATEGORIES = {
    "hosteleria y turismo": [
        "agente de viajes",
        "agente de viajes (diplomado)",
        "aparcacoches",
        "ayudante de camarero",
        "ayudante de cocina",
        "ayudante de cocina curso",
        "azafata de eventos",
        "azafate ave",
        "botones",
        "camarero",
        "cocinero",
        "control pasarelas",
        "coordinador de alumnos",
        "coordinador de carrera",
        "fregaplatos",
        "gobernanta",
        "informacion aeropuerto",
        "mozo maletero",
        "mozo maletero areopuerto",
        "papa noel/paje",
        "recepcion",
        "recepcion hotel",
        "somelier",
        "vendedor de billetes",
        "vigilante parking hotel"
    ],
    "limpieza y servicios auxiliares": [
        "abrillantador suelos",
        "auxiliar oficios varios",
        "ayte office",
        "camarera de piso",
        "conserje",
        "cristalero",
        "lavanderia",
        "limpiador",
        "limpiador de hospitales",
        "limpieza criogenica",
        "limpieza de aviones",
        "limpieza de gruas",
        "limpieza de playas",
        "limpieza de supermercados",
        "limpieza dgf",
        "limpieza especialista",
        "limpieza industrial",
        "limpieza mantenimiento maquinas",
        "limpieza urbana",
        "limpieza zonas comunes",
        "maquinas cristales",
        "operario recogida residuos",
        "supervisor limpieza"
    ],
    "miscelanea / sin categorizar": [
        "abogacia",
        "accesibilidad a tv",
        "acomodador",
        "agente de facturacion",
        "agente oficinas aeropuerto",
        "analista de datos",
        "analista de laboratorio",
        "asistente administrativo",
        "asistente marketing",
        "aux colectividades",
        "aux. de movilidad reducida",
        "aux. informacion",
        "aux.ruta",
        "azafate avion",
        "azafate tren",
        "bedel",
        "cajero",
        "carpinteria",
        "carrista",
        "chef",
        "competencias y motivacion",
        "comunicacion multimedia",
        "conductor de grua",
        "conductor particular",
        "conductor vtc",
        "consultoria",
        "contable",
        "costura",
        "cuidado personas discapacidad",
        "dep. financiero (no usar)",
        "desarrollador de software",
        "dinamica de grupo",
        "directora tienda",
        "disenador",
        "diseno exterior",
        "ejecutivo de ventas",
        "electricista",
        "electronica",
        "empleada de hogar",
        "enfermeria",
        "envasado",
        "especialista en compras (no usar)",
        "estaciones de servicio",
        "etiquetador",
        "fontanero",
        "gerente",
        "gerente de proyectos",
        "gestion de residuos",
        "ingeniero junior",
        "lavado coches",
        "ldo derecho (no usar)",
        "licenciado (no usar)",
        "maletero",
        "manipulador papel ensobrador",
        "matriculacion",
        "mediador intercultural",
        "montador eventos",
        "mozo almacen",
        "mozo de cuadra",
        "n/c",
        "operario de fabrica",
        "operario de produccion",
        "ordenanza",
        "otros",
        "pasarela",
        "patron de cabotaje",
        "patron de marina mercante",
        "peluqueria",
        "peon de triaje",
        "planificador de radio y television",
        "profesor",
        "psicologia",
        "puesto tecnologico (no usar)",
        "recursos humanos",
        "reparador de parkimetros y recaudador",
        "responsable de almacen",
        "responsable de calidad",
        "responsable de servicios",
        "saf",
        "servicios generales (no usar)",
        "supply chain",
        "tecnico de calidad",
        "tecnico de comunicacion",
        "tecnico de operaciones",
        "tecnico de trafico",
        "teleasistencia",
        "traductor",
        "transportista",
        "valet"
    ],
    "educacion y formacion": [
        "administrativo curso",
        "ayudante de camarero curso",
        "camarero curso",
        "cocina curso",
        "colectividades curso",
        "control de accesos curso",
        "educador",
        "estaciones de servicio repsol curso",
        "formador",
        "gerocultor curso",
        "habilidades sociales",
        "limpieza curso",
        "manipulador de alimentos",
        "monitor tiempo libre",
        "monitora de yoga y otras actividades",
        "orientacion laboral",
        "sad curso"
    ],
    "almacen, logistica y transporte": [
        "amr",
        "aux. de ruta",
        "basculista de camiones",
        "carretillero",
        "conductor",
        "conductor autobus",
        "conductor btp",
        "conductor c",
        "conductor de camion c",
        "conductor de empresa",
        "conductor maquinas vending",
        "conductor servicios urbanos",
        "contador mercancias",
        "control de pasaportes",
        "embalaje muebles",
        "gruista",
        "maquinas almacen",
        "mozo de almacen",
        "operario de rampa",
        "peon",
        "preparador pedidos",
        "repartidor",
        "reponedor",
        "tecnico logistica"
    ],
    "mantenimiento y oficios varios": [
        "albanil",
        "calefactor",
        "carpintero",
        "conductor volquete",
        "electricidad",
        "electromecanico",
        "ferralla",
        "fontaneria",
        "frigorista",
        "instalador aa",
        "lector de contadores",
        "mantenimiento",
        "mantenimiento de carreteras",
        "mantenimiento de edificios",
        "mecanico",
        "montador de placas",
        "oficial 1a",
        "oficial 2a",
        "operario de mantenimiento agua",
        "peon de planta agua",
        "pintor",
        "preparador vehiculos",
        "soldador"
    ],
    "especialidades tecnicas y ti": [
        "analista de sistemas",
        "digitalizador",
        "diseno grafico",
        "diseno paginas web",
        "especialista en datos",
        "help desk",
        "mantenimiento informatica",
        "montador de redes",
        "programador",
        "soporte it",
        "tecnico audivisual"
    ],
    "administracion, oficina y finanzas": [
        "administrativo",
        "administrativo de compras",
        "administrativo de obra",
        "administrativo facturacion",
        "administrativo financiero",
        "administrativo sostenibilidad",
        "administrativos relaciones laborales",
        "admtvo contable",
        "archivo",
        "asesor juridico",
        "aux. administrativo",
        "becario",
        "centralita",
        "delineante",
        "estadistico riesgo no financiero",
        "gestion de siniestros",
        "grabador de datos",
        "rrhh",
        "secretaria",
        "tecnico contable",
        "tecnico de nominas",
        "tecnico financiero"
    ],
    "legal, ingenieria y otros profesionales": [
        "abogado",
        "analista",
        "arquitecto",
        "documentalista",
        "ingeniero",
        "interprete",
        "psicologo",
        "tecnico de licitaciones"
    ],
    "comercial y atencion al cliente": [
        "agente",
        "agente de reservas",
        "caja-repo curso",
        "cajera",
        "comercial",
        "comercial de restauracion",
        "dependienta",
        "expendedor gasolinera",
        "fresco-repo curso",
        "peajista",
        "promotora",
        "telemarketing",
        "teleoperador",
        "teleoperador curso"
    ],
    "sanidad y cuidado personal": [
        "aux clinica",
        "aux de enfermeria",
        "auxiliar tecnico de veterinario",
        "ayuda a domicilio",
        "coordinadora sad",
        "enfermera",
        "esteticien",
        "fisioterapeuta",
        "gerocultor",
        "medico",
        "puericultor",
        "tanatoestetica",
        "tecnico de farmacia",
        "trabajadora social"
    ],
    "seguridad y vigilancia": [
        "aux. seguridad",
        "celador",
        "control de accesos",
        "control de probadores",
        "controlador ora",
        "guarda forestal",
        "socorrista",
        "tecnico de emergencias",
        "tecnico de riesgos laborales",
        "vigilante aparcamiento",
        "vigilante comedor",
        "vigilante de seguridad"
    ],
    "construccion y obra": [
        "auxiliar de obra",
        "jefe de obra"
    ],
    "agricultura y jardineria": [
        "aux. jardineria",
        "jardinero",
        "peon agricola",
        "podador",
        "tecnico forestal"
    ],
    "alimentacion y comercio especializado": [
        "carn-pesc curso",
        "carniceria",
        "charcuteria",
        "fruteria",
        "panaderia",
        "pescaderia",
        "productos frescos"
    ]
}