STANDARD_JOB_TITLES = {
    "camarero": ["camarera", "camarero", "restaurant"],
    "ayudante de cocina": ["ayudante de cocina", "ayudante de cocino", "restaurant"],
    "camarera de piso": ["camarera de piso", "camarero de piso"],
    "recepcion hotel": ["recepcion hotel"],
    "cocinero": ["cocinera", "cocinero", "restaurant"],
    "aparcacoches": ["aparcacoches", "restaurant"],
    "maletero": ["mozo maletera", "mozo maletero", "restaurant", "maletero", "acomodar maletas"],
    "fregaplatos": ["fregaplatos", "restaurant"],
    "ayudante de camarero": [
        "ayudante de camarera",
        "ayudante de camarero",
        "restaurant",
    ],
    "vigilante parking hotel": ["restaurant", "vigilante parking hotel"],
    "recepcion": ["recepcion", "restaurant"],
    "mozo maletero areopuerto": [
        "mozo maletero areopuerta",
        "mozo maletero areopuerto",
        "restaurant",
    ],
    "informacion aeropuerto": [
        "informacion aeropuerta",
        "informacion aeropuerto",
        "restaurant",
    ],
    "ayudante de cocina curso": [
        "ayudante de cocina cursa",
        "ayudante de cocina curso",
        "restaurant",
    ],
    "ayudante de camarero curso": [
        "ayudante de camarero cursa",
        "ayudante de camarero curso",
    ],
    "azafate tren": ["azafate ave", "trenes", "servicio tren", "ave", "renfe"],
    "azafate avion": ["azafate avión", "aviones", "vuelos", "ryanair", "aerolineas"],
    "azafata de eventos": ["azafata de eventos", "restaurant"],
    "somelier": ["restaurant", "somelier"],
    "gobernanta": ["gobernanta", "gobernanto", "restaurant"],
    "coordinador de carrera": [
        "coordinador de carrera",
        "coordinador de carrero",
        "restaurant",
    ],
    "coordinador de alumnos": ["coordinador de alumnos", "restaurant"],
    "control pasarelas": ["control pasarelas", "restaurant"],
    "botones": ["botones", "restaurant"],
    "papa noel/paje": ["papa noel/paje", "restaurant"],
    "agente de viajes": ["agente de viajes", "restaurant"],
    "vendedor de billetes": ["restaurant", "vendedor de billetes"],
    "agente de viajes (diplomado)": ["agente de viajes (diplomado)", "restaurant"],
    "limpiador": ["limpiador"],
    "maquinas cristales": ["maquinas cristales"],
    "abrillantador suelos": ["abrillantador suelos"],
    "limpieza urbana": ["limpieza urbana", "limpieza urbano"],
    "conserje": ["conserje"],
    "lavanderia": ["lavanderia", "lavanderio"],
    "supervisor limpieza": ["supervisor limpieza", "supervisor limpiezo"],
    "cristalero": ["cristalera", "cristalero"],
    "limpieza curso": ["limpieza cursa", "limpieza curso"],
    "limpieza dgf": ["limpieza dgf"],
    "limpieza de playas": ["limpieza de playas"],
    "limpieza de gruas": ["limpieza de gruas"],
    "limpieza de aviones": ["limpieza de aviones"],
    "operario recogida residuos": ["operario recogida residuos"],
    "limpieza zonas comunes": ["limpieza zonas comunes"],
    "limpieza criogenica": ["limpieza criogenica", "limpieza criogenico"],
    "limpieza mantenimiento maquinas": ["limpieza mantenimiento maquinas"],
    "limpiador de hospitales": ["limpiador de hospitales"],
    "limpieza de supermercados": ["limpieza de supermercados"],
    "limpieza industrial": ["limpieza industrial"],
    "limpieza especialista": ["limpieza especialista", "limpieza especialisto"],
    "ayte office": ["ayte office"],
    "auxiliar oficios varios": ["auxiliar oficios varios"],
    "peon": ["peon"],
    "mozo de almacen": ["inventario", "moza de almacen", "mozo de almacen"],
    "maquinas almacen": ["maquinas almacen"],
    "conductor autobus": ["conductor autobus"],
    "repartidor": ["repartidor"],
    "gruista": ["gruista", "gruisto"],
    "preparador pedidos": ["preparador pedidos"],
    "conductor de empresa": ["conductor de empresa", "conductor de empreso"],
    "embalaje muebles": ["embalaje muebles"],
    "conductor volquete": ["conductor volquete"],
    "conductor btp": ["conductor btp"],
    "reponedor": ["reponedor"],
    "carretillero": ["carretillera", "carretillero"],
    "conductor servicios urbanos": ["conductor servicios urbanos"],
    "conductor de camion c": ["conductor de camion c"],
    "tecnico logistica": ["logistica", "tecnico logistica", "tecnico logistico"],
    "operario de rampa": ["operario de rampa", "operario de rampo"],
    "amr": ["amr"],
    "control de pasaportes": ["control de pasaportes"],
    "contador mercancias": ["contador mercancias"],
    "basculista de camiones": ["basculista de camiones"],
    "conductor c": ["conductor c"],
    "conductor": ["conductor"],
    "aux. de ruta": ["aux. de ruta", "aux. de ruto"],
    "conductor maquinas vending": ["conductor maquinas vending"],
    "electricidad": ["electricidad"],
    "fontaneria": ["fontaneria", "fontanerio"],
    "mecanico": ["mecanica", "mecanico"],
    "oficial 1a": ["oficial 1a", "oficial 1o"],
    "oficial 2a": ["oficial 2a", "oficial 2o"],
    "carpinteria": ["carpintera", "carpintero"],
    "pintor": ["pintor", "reformas hogar"],
    "soldador": ["soldador"],
    "instalador aa": ["instalador aa", "instalador ao"],
    "montador de placas": ["montador de placas"],
    "mantenimiento de edificios": ["mantenimiento de edificios"],
    "mantenimiento de carreteras": ["mantenimiento de carreteras"],
    "ferralla": ["ferralla", "ferrallo"],
    "frigorista": ["frigorista", "frigoristo"],
    "calefactor": ["calefactor"],
    "lector de contadores": ["lector de contadores"],
    "operario de mantenimiento agua": [
        "operario de mantenimiento agua",
        "operario de mantenimiento aguo",
    ],
    "peon de planta agua": ["peon de planta agua", "peon de planta aguo"],
    "mantenimiento": ["mantenimienta", "mantenimiento"],
    "preparador vehiculos": ["preparador vehiculos"],
    "mantenimiento informatica": [
        "IT",
        "mantenimiento informatica",
        "mantenimiento informatico",
    ],
    "albanil": ["albanil", "cemento", "construcción", "reformas"],
    "electromecanico": ["electromecanica", "electromecanico"],
    "secretaria": [
        "administration",
        "assistant",
        "office",
        "secretaria",
        "secretario",
        "secretary",
    ],
    "aux. administrativo": [
        "administration",
        "assistant",
        "aux. administrativa",
        "aux. administrativo",
        "office",
        "secretary",
    ],
    "gestion de siniestros": [
        "administration",
        "assistant",
        "gestion de siniestros",
        "office",
        "secretary",
    ],
    "centralita": [
        "administration",
        "assistant",
        "centralita",
        "centralito",
        "office",
        "secretary",
    ],
    "archivo": [
        "administration",
        "archiva",
        "archivo",
        "assistant",
        "office",
        "secretary",
    ],
    "admtvo contable": [
        "administration",
        "admtvo contable",
        "assistant",
        "office",
        "secretary",
    ],
    "grabador de datos": [
        "administration",
        "assistant",
        "grabador de datos",
        "office",
        "secretary",
    ],
    "rrhh": ["administration", "assistant", "office", "rrhh", "secretary"],
    "delineante": ["administration", "assistant", "delineante", "office", "secretary"],
    "administrativo de obra": [
        "administration",
        "administrativo de obra",
        "administrativo de obro",
        "assistant",
        "office",
        "secretary",
    ],
    "tecnico contable": [
        "administration",
        "assistant",
        "office",
        "secretary",
        "tecnico contable",
    ],
    "administrativo facturacion": [
        "administration",
        "administrativo facturacion",
        "assistant",
        "office",
        "secretary",
    ],
    "analista": ["analista", "analisto"],
    "administrativo financiero": [
        "administration",
        "administrativo financiera",
        "administrativo financiero",
        "assistant",
        "office",
        "secretary",
    ],
    "estadistico riesgo no financiero": [
        "administration",
        "assistant",
        "estadistico riesgo no financiera",
        "estadistico riesgo no financiero",
        "office",
        "secretary",
    ],
    "administrativo sostenibilidad": [
        "administration",
        "administrativo sostenibilidad",
        "assistant",
        "office",
        "secretary",
    ],
    "tecnico financiero": [
        "administration",
        "assistant",
        "office",
        "secretary",
        "tecnico financiera",
        "tecnico financiero",
    ],
    "tecnico de nominas": [
        "administration",
        "assistant",
        "office",
        "secretary",
        "tecnico de nominas",
    ],
    "administrativo de compras": [
        "administration",
        "administrativo de compras",
        "assistant",
        "office",
        "secretary",
    ],
    "documentalista": ["documentalista", "documentalisto"],
    "administrativo": [
        "administration",
        "administrativa",
        "administrativo",
        "assistant",
        "office",
        "secretary",
    ],
    "asesor juridico": [
        "administration",
        "asesor juridica",
        "asesor juridico",
        "assistant",
        "office",
        "secretary",
    ],
    "administrativos relaciones laborales": [
        "administration",
        "administrativos relaciones laborales",
        "assistant",
        "office",
        "secretary",
    ],
    "becario": [
        "administration",
        "assistant",
        "becaria",
        "becario",
        "office",
        "secretary",
    ],
    "teleoperador": ["teleoperador"],
    "cajera": ["cajera", "cajero"],
    "dependienta": ["dependienta", "dependiento"],
    "comercial": ["comercial","cuentas", "asesor comercial", "ventas", "retail"],
    "telemarketing": ["telemarketing"],
    "caja-repo curso": ["caja-repo cursa", "caja-repo curso"],
    "fresco-repo curso": ["fresco-repo cursa", "fresco-repo curso"],
    "expendedor gasolinera": ["expendedor gasolinera", "expendedor gasolinero"],
    "teleoperador curso": ["teleoperador cursa", "teleoperador curso"],
    "promotora": ["promotora", "promotoro"],
    "agente de facturacion": ["agente de facturacion"],
    "comercial de restauracion": ["comercial de restauracion"],
    "agente de reservas": ["agente de reservas"],
    "agente": ["agente"],
    "peajista": ["peajista", "peajisto"],
    "gerocultor": ["gerocultor"],
    "aux clinica": ["aux clinica", "aux clinico"],
    "ayuda a domicilio": ["ayuda a domicilia", "ayuda a domicilio"],
    "gerocultor curso": ["gerocultor cursa", "gerocultor curso"],
    "cuidado personas discapacidad": ["cuidado personas discapacidad"],
    "fisioterapeuta": ["fisioterapeuta", "fisioterapeuto"],
    "tecnico de farmacia": ["tecnico de farmacia", "tecnico de farmacio"],
    "aux de enfermeria": ["aux de enfermeria", "aux de enfermerio"],
    "puericultor": ["puericultor"],
    "enfermera": ["enfermera", "enfermero"],
    "trabajadora social": ["trabajadora social"],
    "coordinadora sad": ["coordinadora sad"],
    "medico": ["medica", "medico", "fisioterapeuta"],
    "auxiliar tecnico de veterinario": [
        "auxiliar tecnico de veterinaria",
        "auxiliar tecnico de veterinario",
    ],
    "tanatoestetica": ["tanatoestetica", "tanatoestetico"],
    "esteticien": ["esteticien"],
    "controlador ora": ["controlador ora", "controlador oro"],
    "vigilante de seguridad": ["vigilante de seguridad"],
    "aux. seguridad": ["aux. seguridad"],
    "vigilante aparcamiento": ["vigilante aparcamienta", "vigilante aparcamiento"],
    "guarda forestal": ["guarda forestal"],
    "control de accesos": ["control de accesos"],
    "celador": ["celador"],
    "vigilante comedor": ["vigilante comedor"],
    "control de accesos curso": [
        "control de accesos cursa",
        "control de accesos curso",
    ],
    "tecnico de emergencias": ["tecnico de emergencias"],
    "control de probadores": ["control de probadores"],
    "tecnico de riesgos laborales": ["tecnico de riesgos laborales"],
    "socorrista": ["socorrista", "socorristo"],
    "diseno paginas web": ["IT", "diseno paginas web"],
    "montador de redes": ["IT", "montador de redes"],
    "programador": ["IT", "programador"],
    "diseno grafico": ["IT", "diseno grafica", "diseno grafico"],
    "analista de sistemas": ["IT", "analista de sistemas"],
    "help desk": ["IT", "help desk"],
    "tecnico audivisual": ["IT", "tecnico audivisual"],
    "digitalizador": ["IT", "digitalizador"],
    "soporte it": ["IT", "soporte it"],
    "especialista en datos": ["IT", "especialista en datos"],
    "jefe de obra": ["jefe de obra", "jefe de obro"],
    "auxiliar de obra": ["auxiliar de obra", "auxiliar de obro"],
    "jardinero": ["jardinera", "jardinero"],
    "podador": ["podador"],
    "peon agricola": ["peon agricola", "peon agricolo"],
    "aux. jardineria": ["aux. jardineria", "aux. jardinerio"],
    "tecnico forestal": ["tecnico forestal"],
    "productos frescos": ["productos frescos"],
    "fruteria": ["fruteria", "frutero", "frutera"],
    "carniceria": ["carniceria", "carnicero"],
    "pescaderia": ["pescaderia", "pescadero"],
    "panaderia": ["panaderia", "panadero"],
    "charcuteria": ["charcuteria", "charcurtero"],
    "carn-pesc curso": ["carn-pesc cursa", "carn-pesc curso"],
    "orientacion laboral": ["orientacion laboral"],
    "habilidades sociales": ["habilidades sociales"],
    "manipulador de alimentos": ["manipulador de alimentos"],
    "sad curso": ["sad cursa", "sad curso"],
    "cocina curso": ["cocina cursa", "cocina curso"],
    "colectividades curso": ["colectividades cursa", "colectividades curso"],
    "camarero curso": ["camarero cursa", "camarero curso"],
    "estaciones de servicio repsol curso": [
        "estaciones de servicio repsol cursa",
        "estaciones de servicio repsol curso",
    ],
    "formador": ["formador"],
    "administrativo curso": ["administrativo cursa", "administrativo curso"],
    "educador": ["educador"],
    "monitora de yoga y otras actividades": ["monitora de yoga y otras actividades"],
    "monitor tiempo libre": ["monitor tiempo libre"],
    "ingeniero": ["ingeniera", "ingeniero"],
    "arquitecto": ["arquitecta", "arquitecto"],
    "psicologo": ["psicologa", "psicologo"],
    "abogado": ["abogada", "abogado"],
    "tecnico de licitaciones": ["tecnico de licitaciones"],
    "interprete": ["interprete"],
    "n/c": ["n/c"],
    "manipulador papel ensobrador": ["manipulador papel ensobrador"],
    "lavado coches": ["lavado coches"],
    "bedel": ["bedel"],
    "operario de fabrica": ["operario de fabrica", "operario de fabrico"],
    "envasado": ["envasada", "envasado"],
    "gestion de residuos": ["gestion de residuos"],
    "aux. de movilidad reducida": [
        "aux. de movilidad reducida",
        "aux. de movilidad reducido",
    ],
    "empleada de hogar": ["empleada de hogar"],
    "conductor particular": ["conductor particular"],
    "etiquetador": ["etiquetador"],
    "pasarela": ["pasarela", "pasarelo"],
    "aux. informacion": ["aux. informacion"],
    "mediador intercultural": ["mediador intercultural"],
    "aux colectividades": ["aux colectividades"],
    "electronica": ["electronica", "electronico"],
    "planificador de radio y television": ["planificador de radio y television"],
    "comunicacion multimedia": ["comunicacion multimedia", "comunicacion multimedio"],
    "valet": ["valet"],
    "competencias y motivacion": ["competencias y motivacion"],
    "dinamica de grupo": ["dinamica de grupa", "dinamica de grupo"],
    "teleasistencia": ["teleasistencia", "teleasistencio"],
    "agente oficinas aeropuerto": [
        "agente oficinas aeropuerta",
        "agente oficinas aeropuerto",
    ],
    "accesibilidad a tv": ["accesibilidad a tv"],
    "analista de laboratorio": ["analista de laboratoria", "analista de laboratorio"],
    "tecnico de comunicacion": ["tecnico de comunicacion"],
    "patron de cabotaje": ["patron de cabotaje"],
    "patron de marina mercante": ["patron de marina mercante"],
    "matriculacion": ["matriculacion"],
    "responsable de servicios": ["responsable de servicios", "servicios"],
    "peon de triaje": ["peon de triaje"],
    "reparador de parkimetros y recaudador": ["reparador de parkimetros y recaudador"],
    "ordenanza": ["ordenanza", "ordenanzo"],
    "tecnico de operaciones": ["tecnico de operaciones"],
    "tecnico de trafico": ["tecnico de trafica", "tecnico de trafico"],
    "tecnico de calidad": ["tecnico de calidad"],
    "responsable de almacen": ["responsable de almacen"],
    "estaciones de servicio": ["estaciones de servicia", "estaciones de servicio"],
    "cajero": ["cajera", "cajero"],
    "diseno exterior": ["diseno exterior"],
    "directora tienda": ["directora tienda", "directora tiendo"],
    "gerente": ["gerente"],
    "costura": ["costura", "costuro"],
    "traductor": ["traductor"],
    "peluqueria": ["peluqueria", "peluquerio"],
    "acomodador": ["acomodador"],
    "mozo de cuadra": ["mozo de cuadra", "mozo de cuadro"],
    "montador eventos": ["montador eventos"],
    "asistente marketing": ["asistente marketing"],
    "conductor vtc": ["conductor vtc"],
    "responsable de calidad": ["responsable de calidad"],
    "ingeniero junior": ["ingeniero junior"],
    "desarrollador de software": [
        "backend",
        "desarrollador",
        "desarrollador de software",
        "frontend",
        "fullstack",
        "ingeniero de software",
        "programador",
        "software engineer",
    ],
    "analista de datos": [
        "analista de datos",
        "científico de datos",
        "data analyst",
        "data scientist",
        "especialista en datos",
    ],
    "gerente de proyectos": [
        "ceo",
        "coordinador de proyectos",
        "ejecutivo",
        "gerente de proyectos",
        "jefe de proyectos",
        "project manager",
    ],
    "asistente administrativo": [
        "administrativo",
        "asistente administrativo",
        "auxiliar administrativo",
        "encargada",
        "encargado",
        "secretario",
    ],
    "consultoría": [
        "consultor",
        "consultoría",
        "lider de proyectos",
        "calidad"
        "liderazgo",
        "mejora continua",
        "transformación digital",
    ],
    "operario de producción": [
        "operario de maquinas",
        "operario de producción",
        "procesos industriales",
        "producción operario",
        "trabajador de fábrica",
    ],
    "ejecutivo de ventas": [
        "financiero",
        "gestor de cuentas",
        "cuentas",
        "ejecutivo",
        "ejecutivo de ventas",
        "sales representative",
        "sales team",
        "retail",
    ],
    "contable": ["analista contable", "auxiliar contable", "contabilidad", "contable"],
    "mozo almacen": ["almacén", "carretillero", "moza almacen", "mozo almacen"],
    "supply chain": [
        "cadena de suministro",
        "analista logística",
        "supply chain",
        "cadena de producción",
    ],
    "recursos humanos": [
        "gestor de talento",
        "recruitment",
        "recursos humanos",
        "rrhh",
        "seleccionador",
    ],
    "chef": ["chef","cocinero profesional", "cocinero"],
    "psicología": ["psicólogo", "psicóloga", "mental"],
    "enfermería": [
        "clínica",
        "enfermero",
        "farmacia",
        "enfermera",
    ],
    "electricista": [
        "electricista",
        "cables",
        "conexiones electricas",
    ],
    "fontanero": [
        "fontanero",
        "arreglos hogar",
        "cañerias",
        "tuberias",
    ],
    "profesor": [
        "educación",
        "educador",
        "formador",
        "monitor",
        "orientador",
        "profesor",
    ],
    "diseñador": [
        "autocad",
        "diseñador",
        "diseñadora",
        "diseño gráfico",
        "informática",
        "multimedia",
        "solidworks",
        "ux/ui",
    ],

    "conductor de grúa": [
        "conductor",
        "grúa",
    ],
    "transportista": [
        "camionero",
        "camionera",
        "conductor camiones",
    ],
    "abogacia": [
        "abogacia",
        "abogado",
        "asesor jurídico",
        "jurídico",
        "notario",
        "procurador",
    ],
    "otros": ["acomodador", "actor", "funerario", "intérprete", "otros", "traductor"],
}
